-- Gerado por supabase_upload.py --gerar-sql. Pode rodar quantas vezes quiser:
-- so cria o que falta (tabelas novas e colunas novas) e nao apaga nada.
-- Tabelas novas ja nascem com RLS ligado e leitura liberada para usuarios logados.

-- sigitm
do $$ begin
  if to_regclass('public.sigitm') is null then
    create table public.sigitm (id bigint generated by default as identity primary key);
    alter table public.sigitm enable row level security;
    create policy "leitura autenticados" on public.sigitm for select to authenticated using (true);
  end if;
end $$;
alter table public.sigitm
  add column if not exists "vta_pk" text,
  add column if not exists "status" text,
  add column if not exists "raiz" text,
  add column if not exists "empresa_manutencao" text,
  add column if not exists "tipo_de_planta" text,
  add column if not exists "tiquete_referencia" text,
  add column if not exists "tipo_de_alarme" text,
  add column if not exists "tipo_de_bilhete" text,
  add column if not exists "tipo_de_falha" text,
  add column if not exists "nome_site_a" text,
  add column if not exists "nome_site_b" text,
  add column if not exists "sigla_estado" text,
  add column if not exists "nome_municipio" text,
  add column if not exists "nome_estado" text,
  add column if not exists "nome_localidade" text,
  add column if not exists "codigo_gerencia" text,
  add column if not exists "nome_gerencia" text,
  add column if not exists "nome_area" text,
  add column if not exists "tipo_rede" text,
  add column if not exists "baixa_defeito" text,
  add column if not exists "codigo_area" text,
  add column if not exists "codigo_area_dest_optica" text,
  add column if not exists "bairro" text,
  add column if not exists "endereco_falha_optica" text,
  add column if not exists "latitude_falha" text,
  add column if not exists "longitude_falha" text,
  add column if not exists "observacao_historico" text,
  add column if not exists "descricao_da_baixa" text,
  add column if not exists "data_criacao" text,
  add column if not exists "data_de_baixa" text,
  add column if not exists "data_encerramento" text,
  add column if not exists "baixado_por_grupo" text,
  add column if not exists "baixado_por_usuario_nome" text,
  add column if not exists "baixado_por_usuario_login" text,
  add column if not exists "baixado_pela_empresa" text,
  add column if not exists "nome_usuario_responsavel" text,
  add column if not exists "alarme" text,
  add column if not exists "nome_site" text,
  add column if not exists "grupo_responsavel" text,
  add column if not exists "mes_de_criacao_sigitm" text,
  add column if not exists "possui_or_no_sgci" text,
  add column if not exists "possui_ta_raiz" text,
  add column if not exists "possui_endereco_repetido" text,
  add column if not exists "possui_or_no_sgci_mes_atual" text;

-- endereco_repetido_ext_sgtm
do $$ begin
  if to_regclass('public.endereco_repetido_ext_sgtm') is null then
    create table public.endereco_repetido_ext_sgtm (id bigint generated by default as identity primary key);
    alter table public.endereco_repetido_ext_sgtm enable row level security;
    create policy "leitura autenticados" on public.endereco_repetido_ext_sgtm for select to authenticated using (true);
  end if;
end $$;
alter table public.endereco_repetido_ext_sgtm
  add column if not exists "ionix" text,
  add column if not exists "material" text,
  add column if not exists "endereco" text,
  add column if not exists "cabo_qtd" text,
  add column if not exists "cabo_espec" text,
  add column if not exists "emenda" text,
  add column if not exists "status_endereco" text,
  add column if not exists "data_da_criacao_no_sigitim" text,
  add column if not exists "uf" text,
  add column if not exists "possui_material" text;

-- sgci_ate_agosto
do $$ begin
  if to_regclass('public.sgci_ate_agosto') is null then
    create table public.sgci_ate_agosto (id bigint generated by default as identity primary key);
    alter table public.sgci_ate_agosto enable row level security;
    create policy "leitura autenticados" on public.sgci_ate_agosto for select to authenticated using (true);
  end if;
end $$;
alter table public.sgci_ate_agosto
  add column if not exists "contrato_numero" text,
  add column if not exists "contratada" text,
  add column if not exists "escritorio" text,
  add column if not exists "servico_numero" text,
  add column if not exists "ata_de_estudo_previo_titulo" text,
  add column if not exists "servico_tipo" text,
  add column if not exists "servico_sub_tipo" text,
  add column if not exists "servico_ordem_interna" text,
  add column if not exists "medicao_numero" text,
  add column if not exists "medicao_data_da_criacao" text,
  add column if not exists "servico_unitario_codigo" text,
  add column if not exists "medicao_qtde._item_executado" text,
  add column if not exists "medicao_qtde._pontos_a_pagar" text,
  add column if not exists "medicao_valor_a_pagar" text,
  add column if not exists "medicao_classificacao" text,
  add column if not exists "medicao_acesso_atividade" text,
  add column if not exists "medicao_fechamento_do_periodo" text,
  add column if not exists "tipo_de_conta_invest._custeio" text,
  add column if not exists "medicao_tipo_de_mao_de_obra" text,
  add column if not exists "medicao_grupo_nome" text,
  add column if not exists "plano_de_trabalho_numero" text,
  add column if not exists "plano_de_trabalho_nome" text,
  add column if not exists "servico_unitario_descricao" text,
  add column if not exists "ata_de_estudo_previo_aviso_de_comeco" text,
  add column if not exists "ata_de_estudo_previo_aviso_de_termino" text,
  add column if not exists "centro_telefonico" text,
  add column if not exists "medicao_localidade_imposto" text,
  add column if not exists "medicao_autorizado_para_pagamento_sim_nao" text,
  add column if not exists "ata_de_estudo_previo_data_de_inicio" text,
  add column if not exists "ata_de_estudo_previo_data_de_termino" text,
  add column if not exists "medicao_login_do_classificador" text,
  add column if not exists "medicaounidade1" text,
  add column if not exists "medicaounidade2" text,
  add column if not exists "servico_rota" text,
  add column if not exists "servico_boletim_de_anormalidade" text,
  add column if not exists "servico_local_onde_esta_arquivado" text,
  add column if not exists "medicao_data_da_classificacao" text,
  add column if not exists "servico_endereco" text;

-- sgci_mes_atual
do $$ begin
  if to_regclass('public.sgci_mes_atual') is null then
    create table public.sgci_mes_atual (id bigint generated by default as identity primary key);
    alter table public.sgci_mes_atual enable row level security;
    create policy "leitura autenticados" on public.sgci_mes_atual for select to authenticated using (true);
  end if;
end $$;
alter table public.sgci_mes_atual
  add column if not exists "contrato_numero" text,
  add column if not exists "contratada" text,
  add column if not exists "escritorio" text,
  add column if not exists "servico_numero" text,
  add column if not exists "ata_de_estudo_previo_titulo" text,
  add column if not exists "servico_tipo" text,
  add column if not exists "servico_sub_tipo" text,
  add column if not exists "servico_ordem_interna" text,
  add column if not exists "medicao_numero" text,
  add column if not exists "medicao_data_da_criacao" text,
  add column if not exists "servico_unitario_codigo" text,
  add column if not exists "medicao_qtde._item_executado" text,
  add column if not exists "medicao_qtde._pontos_a_pagar" text,
  add column if not exists "medicao_valor_a_pagar" text,
  add column if not exists "medicao_classificacao" text,
  add column if not exists "medicao_acesso_atividade" text,
  add column if not exists "medicao_fechamento_do_periodo" text,
  add column if not exists "tipo_de_conta_invest._custeio" text,
  add column if not exists "medicao_tipo_de_mao_de_obra" text,
  add column if not exists "medicao_grupo_nome" text,
  add column if not exists "plano_de_trabalho_numero" text,
  add column if not exists "plano_de_trabalho_nome" text,
  add column if not exists "servico_unitario_descricao" text,
  add column if not exists "ata_de_estudo_previo_aviso_de_comeco" text,
  add column if not exists "ata_de_estudo_previo_aviso_de_termino" text,
  add column if not exists "centro_telefonico" text,
  add column if not exists "medicao_localidade_imposto" text,
  add column if not exists "medicao_autorizado_para_pagamento_sim_nao" text,
  add column if not exists "ata_de_estudo_previo_data_de_inicio" text,
  add column if not exists "ata_de_estudo_previo_data_de_termino" text,
  add column if not exists "medicao_login_do_classificador" text,
  add column if not exists "medicaounidade1" text,
  add column if not exists "medicaounidade2" text,
  add column if not exists "servico_rota" text,
  add column if not exists "servico_boletim_de_anormalidade" text,
  add column if not exists "servico_local_onde_esta_arquivado" text,
  add column if not exists "medicao_data_da_classificacao" text,
  add column if not exists "servico_endereco" text;

-- codigos_de_servico
do $$ begin
  if to_regclass('public.codigos_de_servico') is null then
    create table public.codigos_de_servico (id bigint generated by default as identity primary key);
    alter table public.codigos_de_servico enable row level security;
    create policy "leitura autenticados" on public.codigos_de_servico for select to authenticated using (true);
  end if;
end $$;
alter table public.codigos_de_servico
  add column if not exists "servico_numero" text,
  add column if not exists "servico_unitario_descricao" text;
