-- Gerado por supabase_upload.py --gerar-sql. Pode rodar quantas vezes quiser:
-- so cria o que falta (tabelas novas e colunas novas) e nao apaga nada.
-- Tabelas novas ja nascem com RLS ligado e leitura liberada para usuarios logados.

-- sigitm
do $$ begin
  if to_regclass('public.sigitm') is null then
    create table public.sigitm (id bigint generated by default as identity primary key);
    alter table public.sigitm enable row level security;
    create policy "leitura autenticados" on public.sigitm for select to authenticated using (true);
  end if;
end $$;
alter table public.sigitm
  add column if not exists "vta_pk" text,
  add column if not exists "status" text,
  add column if not exists "raiz" text,
  add column if not exists "empresa_manutencao" text,
  add column if not exists "tipo_de_planta" text,
  add column if not exists "tiquete_referencia" text,
  add column if not exists "tipo_de_alarme" text,
  add column if not exists "tipo_de_bilhete" text,
  add column if not exists "tipo_de_falha" text,
  add column if not exists "nome_site_a" text,
  add column if not exists "nome_site_b" text,
  add column if not exists "sigla_estado" text,
  add column if not exists "nome_municipio" text,
  add column if not exists "nome_estado" text,
  add column if not exists "nome_localidade" text,
  add column if not exists "codigo_gerencia" text,
  add column if not exists "nome_gerencia" text,
  add column if not exists "nome_area" text,
  add column if not exists "tipo_rede" text,
  add column if not exists "baixa_defeito" text,
  add column if not exists "codigo_area" text,
  add column if not exists "codigo_area_dest_optica" text,
  add column if not exists "bairro" text,
  add column if not exists "endereco_falha_optica" text,
  add column if not exists "latitude_falha" text,
  add column if not exists "longitude_falha" text,
  add column if not exists "observacao_historico" text,
  add column if not exists "descricao_da_baixa" text,
  add column if not exists "data_criacao" text,
  add column if not exists "data_de_baixa" text,
  add column if not exists "data_encerramento" text,
  add column if not exists "baixado_por_grupo" text,
  add column if not exists "baixado_por_usuario_nome" text,
  add column if not exists "baixado_por_usuario_login" text,
  add column if not exists "baixado_pela_empresa" text,
  add column if not exists "nome_usuario_responsavel" text,
  add column if not exists "alarme" text,
  add column if not exists "nome_site" text,
  add column if not exists "grupo_responsavel" text,
  add column if not exists "mes_de_criacao_sigitm" text,
  add column if not exists "possui_or_no_sgci" text,
  add column if not exists "possui_ta_raiz" text,
  add column if not exists "possui_endereco_repetido" text,
  add column if not exists "possui_or_no_sgci_mes_atual" text;

-- endereco_repetido_ext_sgtm
do $$ begin
  if to_regclass('public.endereco_repetido_ext_sgtm') is null then
    create table public.endereco_repetido_ext_sgtm (id bigint generated by default as identity primary key);
    alter table public.endereco_repetido_ext_sgtm enable row level security;
    create policy "leitura autenticados" on public.endereco_repetido_ext_sgtm for select to authenticated using (true);
  end if;
end $$;
alter table public.endereco_repetido_ext_sgtm
  add column if not exists "ionix" text,
  add column if not exists "material" text,
  add column if not exists "endereco" text,
  add column if not exists "cabo_qtd" text,
  add column if not exists "cabo_espec" text,
  add column if not exists "emenda" text,
  add column if not exists "status_endereco" text,
  add column if not exists "data_da_criacao_no_sigitim" text,
  add column if not exists "uf" text,
  add column if not exists "possui_material" text;

-- sgci_ate_agosto
do $$ begin
  if to_regclass('public.sgci_ate_agosto') is null then
    create table public.sgci_ate_agosto (id bigint generated by default as identity primary key);
    alter table public.sgci_ate_agosto enable row level security;
    create policy "leitura autenticados" on public.sgci_ate_agosto for select to authenticated using (true);
  end if;
end $$;
alter table public.sgci_ate_agosto
  add column if not exists "contrato_numero" text,
  add column if not exists "contratada" text,
  add column if not exists "escritorio" text,
  add column if not exists "servico_numero" text,
  add column if not exists "ata_de_estudo_previo_titulo" text,
  add column if not exists "servico_tipo" text,
  add column if not exists "servico_sub_tipo" text,
  add column if not exists "servico_ordem_interna" text,
  add column if not exists "medicao_numero" text,
  add column if not exists "medicao_data_da_criacao" text,
  add column if not exists "servico_unitario_codigo" text,
  add column if not exists "medicao_qtde._item_executado" text,
  add column if not exists "medicao_qtde._pontos_a_pagar" text,
  add column if not exists "medicao_valor_a_pagar" text,
  add column if not exists "medicao_classificacao" text,
  add column if not exists "medicao_acesso_atividade" text,
  add column if not exists "medicao_fechamento_do_periodo" text,
  add column if not exists "tipo_de_conta_invest._custeio" text,
  add column if not exists "medicao_tipo_de_mao_de_obra" text,
  add column if not exists "medicao_grupo_nome" text,
  add column if not exists "plano_de_trabalho_numero" text,
  add column if not exists "plano_de_trabalho_nome" text,
  add column if not exists "servico_unitario_descricao" text,
  add column if not exists "ata_de_estudo_previo_aviso_de_comeco" text,
  add column if not exists "ata_de_estudo_previo_aviso_de_termino" text,
  add column if not exists "centro_telefonico" text,
  add column if not exists "medicao_localidade_imposto" text,
  add column if not exists "medicao_autorizado_para_pagamento_sim_nao" text,
  add column if not exists "ata_de_estudo_previo_data_de_inicio" text,
  add column if not exists "ata_de_estudo_previo_data_de_termino" text,
  add column if not exists "medicao_login_do_classificador" text,
  add column if not exists "medicaounidade1" text,
  add column if not exists "medicaounidade2" text,
  add column if not exists "servico_rota" text,
  add column if not exists "servico_boletim_de_anormalidade" text,
  add column if not exists "servico_local_onde_esta_arquivado" text,
  add column if not exists "medicao_data_da_classificacao" text,
  add column if not exists "servico_endereco" text;

-- sgci_mes_atual
do $$ begin
  if to_regclass('public.sgci_mes_atual') is null then
    create table public.sgci_mes_atual (id bigint generated by default as identity primary key);
    alter table public.sgci_mes_atual enable row level security;
    create policy "leitura autenticados" on public.sgci_mes_atual for select to authenticated using (true);
  end if;
end $$;
alter table public.sgci_mes_atual
  add column if not exists "contrato_numero" text,
  add column if not exists "contratada" text,
  add column if not exists "escritorio" text,
  add column if not exists "servico_numero" text,
  add column if not exists "ata_de_estudo_previo_titulo" text,
  add column if not exists "servico_tipo" text,
  add column if not exists "servico_sub_tipo" text,
  add column if not exists "servico_ordem_interna" text,
  add column if not exists "medicao_numero" text,
  add column if not exists "medicao_data_da_criacao" text,
  add column if not exists "servico_unitario_codigo" text,
  add column if not exists "medicao_qtde._item_executado" text,
  add column if not exists "medicao_qtde._pontos_a_pagar" text,
  add column if not exists "medicao_valor_a_pagar" text,
  add column if not exists "medicao_classificacao" text,
  add column if not exists "medicao_acesso_atividade" text,
  add column if not exists "medicao_fechamento_do_periodo" text,
  add column if not exists "tipo_de_conta_invest._custeio" text,
  add column if not exists "medicao_tipo_de_mao_de_obra" text,
  add column if not exists "medicao_grupo_nome" text,
  add column if not exists "plano_de_trabalho_numero" text,
  add column if not exists "plano_de_trabalho_nome" text,
  add column if not exists "servico_unitario_descricao" text,
  add column if not exists "ata_de_estudo_previo_aviso_de_comeco" text,
  add column if not exists "ata_de_estudo_previo_aviso_de_termino" text,
  add column if not exists "centro_telefonico" text,
  add column if not exists "medicao_localidade_imposto" text,
  add column if not exists "medicao_autorizado_para_pagamento_sim_nao" text,
  add column if not exists "ata_de_estudo_previo_data_de_inicio" text,
  add column if not exists "ata_de_estudo_previo_data_de_termino" text,
  add column if not exists "medicao_login_do_classificador" text,
  add column if not exists "medicaounidade1" text,
  add column if not exists "medicaounidade2" text,
  add column if not exists "servico_rota" text,
  add column if not exists "servico_boletim_de_anormalidade" text,
  add column if not exists "servico_local_onde_esta_arquivado" text,
  add column if not exists "medicao_data_da_classificacao" text,
  add column if not exists "servico_endereco" text;

-- codigos_de_servico
do $$ begin
  if to_regclass('public.codigos_de_servico') is null then
    create table public.codigos_de_servico (id bigint generated by default as identity primary key);
    alter table public.codigos_de_servico enable row level security;
    create policy "leitura autenticados" on public.codigos_de_servico for select to authenticated using (true);
  end if;
end $$;
alter table public.codigos_de_servico
  add column if not exists "servico_numero" text,
  add column if not exists "servico_unitario_descricao" text;

-- saldo_dia
do $$ begin
  if to_regclass('public.saldo_dia') is null then
    create table public.saldo_dia (id bigint generated by default as identity primary key);
    alter table public.saldo_dia enable row level security;
    create policy "leitura autenticados" on public.saldo_dia for select to authenticated using (true);
  end if;
end $$;
alter table public.saldo_dia
  add column if not exists "centro" text,
  add column if not exists "uf" text,
  add column if not exists "deposito" text,
  add column if not exists "material" text,
  add column if not exists "texto_breve_material" text,
  add column if not exists "utilizacao_livre" text,
  add column if not exists "lote" text,
  add column if not exists "val.utiliz.livre" text;

-- material_aberto
do $$ begin
  if to_regclass('public.material_aberto') is null then
    create table public.material_aberto (id bigint generated by default as identity primary key);
    alter table public.material_aberto enable row level security;
    create policy "leitura autenticados" on public.material_aberto for select to authenticated using (true);
  end if;
end $$;
alter table public.material_aberto
  add column if not exists "contrato" text,
  add column if not exists "escritorio" text,
  add column if not exists "centro_telefonico" text,
  add column if not exists "servico" text,
  add column if not exists "tipo" text,
  add column if not exists "sub_tipo" text,
  add column if not exists "ordem_interna" text,
  add column if not exists "plano_de_trabalho" text,
  add column if not exists "b.a." text,
  add column if not exists "ata" text,
  add column if not exists "medicao" text,
  add column if not exists "data_de_cadastro_do_material" text,
  add column if not exists "no_de_estoque" text,
  add column if not exists "descricao_do_material" text,
  add column if not exists "unidade" text,
  add column if not exists "lote" text,
  add column if not exists "bobina" text,
  add column if not exists "quantidade" text,
  add column if not exists "valor_unitario" text,
  add column if not exists "valor_r$" text,
  add column if not exists "classificacao" text,
  add column if not exists "codigo_da_ud" text,
  add column if not exists "tipo_de_mao_de_obra" text,
  add column if not exists "ponto_baremo" text,
  add column if not exists "pontos" text;

-- material_fechado
do $$ begin
  if to_regclass('public.material_fechado') is null then
    create table public.material_fechado (id bigint generated by default as identity primary key);
    alter table public.material_fechado enable row level security;
    create policy "leitura autenticados" on public.material_fechado for select to authenticated using (true);
  end if;
end $$;
alter table public.material_fechado
  add column if not exists "contrato" text,
  add column if not exists "escritorio" text,
  add column if not exists "centro_telefonico" text,
  add column if not exists "servico" text,
  add column if not exists "tipo" text,
  add column if not exists "sub_tipo" text,
  add column if not exists "ordem_interna" text,
  add column if not exists "plano_de_trabalho" text,
  add column if not exists "b.a." text,
  add column if not exists "ata" text,
  add column if not exists "medicao" text,
  add column if not exists "data_de_cadastro_do_material" text,
  add column if not exists "no_de_estoque" text,
  add column if not exists "descricao_do_material" text,
  add column if not exists "unidade" text,
  add column if not exists "lote" text,
  add column if not exists "bobina" text,
  add column if not exists "quantidade" text,
  add column if not exists "valor_unitario" text,
  add column if not exists "valor_r$" text,
  add column if not exists "classificacao" text,
  add column if not exists "codigo_da_ud" text,
  add column if not exists "tipo_de_mao_de_obra" text,
  add column if not exists "ponto_baremo" text,
  add column if not exists "pontos" text;

-- codigos_de_material
do $$ begin
  if to_regclass('public.codigos_de_material') is null then
    create table public.codigos_de_material (id bigint generated by default as identity primary key);
    alter table public.codigos_de_material enable row level security;
    create policy "leitura autenticados" on public.codigos_de_material for select to authenticated using (true);
  end if;
end $$;
alter table public.codigos_de_material
  add column if not exists "codigo" text,
  add column if not exists "descricao_do_material" text;

-- base_mnt_sc
do $$ begin
  if to_regclass('public.base_mnt_sc') is null then
    create table public.base_mnt_sc (id bigint generated by default as identity primary key);
    alter table public.base_mnt_sc enable row level security;
    create policy "leitura autenticados" on public.base_mnt_sc for select to authenticated using (true);
  end if;
end $$;
alter table public.base_mnt_sc
  add column if not exists "id_planilha" text,
  add column if not exists "ionix" text,
  add column if not exists "ta" text,
  add column if not exists "status" text,
  add column if not exists "atividade" text,
  add column if not exists "responsavel_fibra" text,
  add column if not exists "uf" text,
  add column if not exists "cidade" text,
  add column if not exists "cluster" text,
  add column if not exists "armario" text,
  add column if not exists "motivo" text,
  add column if not exists "causa_raiz" text,
  add column if not exists "data_abertura" text,
  add column if not exists "evento_reecebido" text,
  add column if not exists "data_acionado_eps" text,
  add column if not exists "data_encerrado" text,
  add column if not exists "data_concluido" text,
  add column if not exists "ttr" text,
  add column if not exists "tmr" text,
  add column if not exists "sla" text,
  add column if not exists "empreiteira" text,
  add column if not exists "tipo_de_cabo" text,
  add column if not exists "metragem" text,
  add column if not exists "quantidade_de_postes" text,
  add column if not exists "tecnologia" text,
  add column if not exists "endereco" text,
  add column if not exists "supervisor_responsavel" text,
  add column if not exists "observacao" text,
  add column if not exists "area" text,
  add column if not exists "escritorio" text,
  add column if not exists "contrato" text,
  add column if not exists "servicos_materiais" text,
  add column if not exists "quantidade" text,
  add column if not exists "tipo_evento" text,
  add column if not exists "tipo_registro" text;

-- almox_sc
do $$ begin
  if to_regclass('public.almox_sc') is null then
    create table public.almox_sc (id bigint generated by default as identity primary key);
    alter table public.almox_sc enable row level security;
    create policy "leitura autenticados" on public.almox_sc for select to authenticated using (true);
  end if;
end $$;
alter table public.almox_sc
  add column if not exists "codigo" text,
  add column if not exists "material" text,
  add column if not exists "saldo" text,
  add column if not exists "um" text,
  add column if not exists "lote" text,
  add column if not exists "centro" text,
  add column if not exists "deposito" text,
  add column if not exists "cluster" text;

-- b2b_sc
do $$ begin
  if to_regclass('public.b2b_sc') is null then
    create table public.b2b_sc (id bigint generated by default as identity primary key);
    alter table public.b2b_sc enable row level security;
    create policy "leitura autenticados" on public.b2b_sc for select to authenticated using (true);
  end if;
end $$;
alter table public.b2b_sc
  add column if not exists "projeto" text,
  add column if not exists "projetista" text,
  add column if not exists "projeto_autocad" text,
  add column if not exists "responsavel" text,
  add column if not exists "entregue" text,
  add column if not exists "recebido" text,
  add column if not exists "previsao" text,
  add column if not exists "prazo" text;

-- ofensores_rs
do $$ begin
  if to_regclass('public.ofensores_rs') is null then
    create table public.ofensores_rs (id bigint generated by default as identity primary key);
    alter table public.ofensores_rs enable row level security;
    create policy "leitura autenticados" on public.ofensores_rs for select to authenticated using (true);
  end if;
end $$;
alter table public.ofensores_rs
  add column if not exists "ard" text,
  add column if not exists "elemento" text,
  add column if not exists "rede" text,
  add column if not exists "selo" text,
  add column if not exists "id_planilha" text,
  add column if not exists "valor_tlp" text,
  add column if not exists "valor_parceiro" text,
  add column if not exists "executor" text,
  add column if not exists "medicao" text,
  add column if not exists "status_aceite_osp" text,
  add column if not exists "equipe" text,
  add column if not exists "inicio" text,
  add column if not exists "fim" text,
  add column if not exists "status_campo" text,
  add column if not exists "observacao" text,
  add column if not exists "evidencias" text,
  add column if not exists "vistoria" text,
  add column if not exists "status_draft" text,
  add column if not exists "status_medicao" text,
  add column if not exists "valor_mo" text,
  add column if not exists "valor_material" text,
  add column if not exists "valor_total_orcado" text,
  add column if not exists "valor_total_medido_mo" text,
  add column if not exists "valor_total_faturado" text;

-- desligue_cobre
do $$ begin
  if to_regclass('public.desligue_cobre') is null then
    create table public.desligue_cobre (id bigint generated by default as identity primary key);
    alter table public.desligue_cobre enable row level security;
    create policy "leitura autenticados" on public.desligue_cobre for select to authenticated using (true);
  end if;
end $$;
alter table public.desligue_cobre
  add column if not exists "id_planilha" text,
  add column if not exists "projeto" text,
  add column if not exists "tlpcp" text,
  add column if not exists "uf" text,
  add column if not exists "cidade" text,
  add column if not exists "obra" text,
  add column if not exists "obs" text,
  add column if not exists "prioridade" text,
  add column if not exists "status_campo" text,
  add column if not exists "status_draft" text,
  add column if not exists "valor_orcado" text,
  add column if not exists "status_medicao" text,
  add column if not exists "valor_medido" text,
  add column if not exists "valor_faturado" text;

-- ofensores_sc
do $$ begin
  if to_regclass('public.ofensores_sc') is null then
    create table public.ofensores_sc (id bigint generated by default as identity primary key);
    alter table public.ofensores_sc enable row level security;
    create policy "leitura autenticados" on public.ofensores_sc for select to authenticated using (true);
  end if;
end $$;
alter table public.ofensores_sc
  add column if not exists "programacao" text,
  add column if not exists "regional" text,
  add column if not exists "acao_mapeada" text,
  add column if not exists "id_obra" text,
  add column if not exists "primarias" text,
  add column if not exists "responsavel" text,
  add column if not exists "cluster" text,
  add column if not exists "contrato" text,
  add column if not exists "armario" text,
  add column if not exists "draft" text,
  add column if not exists "status_splitter" text,
  add column if not exists "status_id" text,
  add column if not exists "status_draft" text,
  add column if not exists "previsao_enrega_draft" text,
  add column if not exists "valor_mo" text,
  add column if not exists "valor_material" text,
  add column if not exists "valor_total_orcado" text,
  add column if not exists "status_medicao" text,
  add column if not exists "valor_total_medido" text,
  add column if not exists "valor_faturado_total" text,
  add column if not exists "pedido" text,
  add column if not exists "draft_1" text,
  add column if not exists "medicao" text;

-- prumadas
do $$ begin
  if to_regclass('public.prumadas') is null then
    create table public.prumadas (id bigint generated by default as identity primary key);
    alter table public.prumadas enable row level security;
    create policy "leitura autenticados" on public.prumadas for select to authenticated using (true);
  end if;
end $$;
alter table public.prumadas
  add column if not exists "uf" text,
  add column if not exists "observacao" text,
  add column if not exists "parceiro" text,
  add column if not exists "id_osp" text,
  add column if not exists "codigo_pruma" text,
  add column if not exists "endereco" text,
  add column if not exists "fila_pruma" text,
  add column if not exists "data" text,
  add column if not exists "fila_draft" text,
  add column if not exists "fila_medicao" text,
  add column if not exists "contrato" text,
  add column if not exists "os" text,
  add column if not exists "drop_4fo_mts" text,
  add column if not exists "cabo_drop_24f" text,
  add column if not exists "cabo_drop_12_5mm" text,
  add column if not exists "cabo_drrop_12_100m" text,
  add column if not exists "cabo_drrop_12_200m" text,
  add column if not exists "cabo_drrop_12_250m" text,
  add column if not exists "cabo_drrop_12_300m2" text,
  add column if not exists "cabo_drrop_12_150pm" text,
  add column if not exists "cx_transicao" text,
  add column if not exists "conector_externo" text,
  add column if not exists "conector_interno" text,
  add column if not exists "mini_cdoe_90:10" text,
  add column if not exists "mini_cdoe_85:15" text,
  add column if not exists "mini_cdoe_80:20" text,
  add column if not exists "mini_cdoe_70:30" text,
  add column if not exists "mini_cdoe_60:40" text,
  add column if not exists "mini_cdoe_1:8" text,
  add column if not exists "cenario_4" text,
  add column if not exists "valor_empresa" text,
  add column if not exists "valor_parceiro" text,
  add column if not exists "adicional_4" text,
  add column if not exists "valor2" text,
  add column if not exists "valor_parceiro2" text,
  add column if not exists "adicional_4_1" text,
  add column if not exists "valor3" text,
  add column if not exists "valor_parceiro22" text,
  add column if not exists "cenario_2" text,
  add column if not exists "valor_2" text,
  add column if not exists "valor_parceiro23" text,
  add column if not exists "adicional_2" text,
  add column if not exists "valor_2_1" text,
  add column if not exists "valor_parceiro24" text,
  add column if not exists "adicional_2_1" text,
  add column if not exists "valor2_1" text,
  add column if not exists "valor_parceiro25" text,
  add column if not exists "total" text,
  add column if not exists "valor_parceiro26" text,
  add column if not exists "medicao_enviada_ao_parceiro" text,
  add column if not exists "coluna1" text;

-- historico_ano_mnt_sc
do $$ begin
  if to_regclass('public.historico_ano_mnt_sc') is null then
    create table public.historico_ano_mnt_sc (id bigint generated by default as identity primary key);
    alter table public.historico_ano_mnt_sc enable row level security;
    create policy "leitura autenticados" on public.historico_ano_mnt_sc for select to authenticated using (true);
  end if;
end $$;
alter table public.historico_ano_mnt_sc
  add column if not exists "id_planilha" text,
  add column if not exists "ionix" text,
  add column if not exists "status" text,
  add column if not exists "atividade" text,
  add column if not exists "responsavel_fibra" text,
  add column if not exists "uf" text,
  add column if not exists "cidade" text,
  add column if not exists "cluster" text,
  add column if not exists "armario" text,
  add column if not exists "motivo" text,
  add column if not exists "causa_raiz" text,
  add column if not exists "data_abertura" text,
  add column if not exists "evento_reecebido" text,
  add column if not exists "data_acionado_eps" text,
  add column if not exists "data_encerrado" text,
  add column if not exists "data_concluido" text,
  add column if not exists "ttr" text,
  add column if not exists "tmr" text,
  add column if not exists "sla" text,
  add column if not exists "empreiteira" text,
  add column if not exists "tipo_de_cabo" text;
